#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/diary_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: your_db_username
#    password: your_db_password
#  jpa:
#    hibernate:
#      ddl-auto: update  # 자동으로 DB 스키마 업데이트
#    show-sql: true       # 실행되는 SQL 로그 출력
#    properties:
#      hibernate:
#        format_sql: true  # SQL 포맷팅 (보여주기 좋게)
#  servlet:
#    multipart:
#      max-file-size: 10MB  # 파일 업로드 제한
#      max-request-size: 10MB
#
#server:
#  port: 8080  # 서버 포트 설정
